org: laislopes
app: students-batch-record
service: students-batch-record
frameworkVersion: '3'

resources:
  extensions:
    S3BucketStudentscsvbatch:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - POST
                - PUT
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
params:
  dev:
    apiBaseUrl: http://localhost:3003
  prod:
    apiBaseUrl: http://ec2-18-230-184-190.sa-east-1.compute.amazonaws.com:3000

provider:
  name: aws
  runtime: nodejs18.x
  iam: 
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::students-csv-batch/*
  environment:
    API_BASE_URL: ${param:apiBaseUrl}
  

functions:
  registerStudents:
    handler: batch_record/aws/index.registerStudents
    events:
      - s3: 
          bucket: students-csv-batch
          event: s3:ObjectCreated:*
          rules: 
            - suffix: .csv

  simulatingCSVUpload:
    handler: batch_record/local/index.simulatingCSVUpload
    events:
      - httpApi:
          path: /students/batch
          method: post
    enabled: false

  registerStudentsFromLocalBucket:
    handler: batch_record/local/index.registerStudentsFromLocalBucket
    events:
      - s3: 
          bucket: students-csv-local
          event: s3:ObjectCreated:*
          rules: 
            - suffix: .csv
    enabled: false

plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-disable-functions