org: laislopes
app: students-batch-record
service: students-batch-record
frameworkVersion: '3'

resources:
  extensions:
    S3BucketStudentscsv:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - POST
                - PUT
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
            
provider:
  name: aws
  runtime: nodejs18.x
  iam: 
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::students-csv/*

functions:
  registerStudents:
    handler: register_batch/aws/index.registerStudents
    events:
      - s3: 
          bucket: students-csv
          event: s3:ObjectCreated:*
          rules: 
            - suffix: .csv

  simulatingCSVUpload:
    handler: register_batch/local/index.simulatingCSVUpload
    events:
      - httpApi:
          path: /students/batch
          method: post
    enabled: false

  registerStudentsFromLocalBucket:
    handler: register_batch/local/index.registerStudentsFromLocalBucket
    events:
      - s3: 
          bucket: students-csv-local
          event: s3:ObjectCreated:*
          rules: 
            - suffix: .csv
    enabled: false

plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-disable-functions